<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UMSBFMM" name="com.training.regression.tests.CategoryAndCourse_ELTC_075" tests="3" failures="0" timestamp="17 Jul 2019 06:21:36 GMT" time="12.011" errors="1">
  <testcase name="validCreateCategoryTest" time="0.000" classname="com.training.regression.tests.CategoryAndCourse_ELTC_075">
    <error type="java.lang.RuntimeException" message="Can&#039;t invoke method public java.lang.Object[][] com.training.dataproviders.TestDataProvider.getExcelData() on this instance of class com.training.regression.tests.CategoryAndCourse_ELTC_075 due to class mismatch">
      <![CDATA[java.lang.RuntimeException: Can't invoke method public java.lang.Object[][] com.training.dataproviders.TestDataProvider.getExcelData() on this instance of class com.training.regression.tests.CategoryAndCourse_ELTC_075 due to class mismatch
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:75)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1276)
	at org.testng.internal.Invoker.createParameters(Invoker.java:991)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1081)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- validCreateCategoryTest -->
  <testcase name="validLogoutTest" time="4.001" classname="com.training.regression.tests.CategoryAndCourse_ELTC_075"/>
  <testcase name="validLoginTest" time="8.010" classname="com.training.regression.tests.CategoryAndCourse_ELTC_075"/>
</testsuite> <!-- com.training.regression.tests.CategoryAndCourse_ELTC_075 -->
